GET http://localhost:3000/getRecords HTTP/1.1


### Get single record with an ID
GET http://localhost:3000/getRecord?id=45 HTTP/1.1


### Get single record with an ID
GET http://localhost:3000/getRawMaterial?id=52 HTTP/1.1

### Get single record with an ID
GET http://localhost:3000/getHP?id=45 HTTP/1.1

### Adding a record
POST http://localhost:3000/addExperimentRecord HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "record": {
        "experimentRecord": {
            "LOT_NO": "22222",
            "project_title": "2nd Title",
            "formulation_date": "2020-07-12",
            "preparation_date": "2020-05-5",
            "prepared_by": "John",
            "quantity": "400",
            "notes": "Take 100g and Test stability in 54C for 2 weeks\nTake 100g and Test stability in 50C for 35 days\nProvide 100g to Sean/Cesar to conduct corrosion testing on Brass.",
            "preparation_reason": "To test improved F/T performance and reduce corrosion of the RTU formula while making it fall under our newly filed patents",
            "observations" : null,
            "total_percentage_w": "100.0",
            "total_AR": "125.6",
            "total_AD": "35.84",
            "date_created": "2020-06-25"
        },
        "RMList": [{
                "raw_material_name": "chemical L63",
                "percentage_w": 11.11,
                "raw_material_lot": " ",
                "AR": 44.44,
                "AD": 44.48,
                "time_added": "2020-06-25",
                "notes": "none"
            },
            {
                "raw_material_name": "H2O2 50% EPA",
                "percentage_w": 21.11,
                "raw_material_lot": " ",
                "AR": 55.44,
                "AD": 44.48,
                "time_added": "2020-06-24",
                "notes": "none"
            }
        ],
        "HPList": [{
                "experiment_name": "Trial 1",
                "N": 0.1000,
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "~ 0.8%",
                "date": "2020-06-25",
                "initials": "J.K"
            },
            {
                "experiment_name": "Trial 2",
                "N": "",
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "",
                "date": "2020-12-5",
                "initials": ""
            },
            {
                "experiment_name": "Average",
                "N": "",
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "",
                "date": null,
                "initials": ""
            }
        ],
        "HPStabilityList": [{
                "experiment_name": "Trial 1",
                "N": 0.1000,
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "~ 0.8%",
                "date": "2020-05-15",
                "initials": "J.K"
            },
            {
                "experiment_name": "Trial 2",
                "N": "",
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "",
                "date": "2020-12-5",
                "initials": ""
            }
        ]
    }
    
}

### Adding Raw materials 
POST http://localhost:3000/addRawMaterial HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "record": {
        "experimentRecord": {
            "record_id": 52
        },
        "RMList": [{
                "raw_material_name": "chemical L63",
                "percentage_w": 11.11,
                "raw_material_lot": " ",
                "AR": 44.44,
                "AD": 44.48,
                "time_added": "2020-12-5",
                "notes": "this is an update"
            },
            {
                "raw_material_name": "H2O2 50% EPA",
                "percentage_w": 21.11,
                "raw_material_lot": " ",
                "AR": 55.44,
                "AD": 44.48,
                "time_added": "2020-12-5",
                "notes": "this is another update"
            }
        ]
    }
}

### Adding Hydrogen Peroxide data
POST http://localhost:3000/addHP HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "record": {
        "experimentRecord": {
            "record_id": 52
        },
        "HPList": [{
                "experiment_name": "Trial 1",
                "N": 0.1000,
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "~ 0.8%",
                "date": "2020-12-5",
                "initials": "D.C"
            },
            {
                "experiment_name": "Trial 2",
                "N": "",
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "new range",
                "date": "2020-12-5",
                "initials": ""
            },
            {
                "experiment_name": "Average (Updated)",
                "N": "",
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "",
                "date": null,
                "initials": "D.C"
            }
        ],
        "HPStabilityList": [{
                "experiment_name": "Trial 1",
                "N": 0.1000,
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "~ 0.75%",
                "date": "2020-12-5",
                "initials": "J.K"
            },
            {
                "experiment_name": "Trial 2",
                "N": "",
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "",
                "date": "2020-12-5",
                "initials": "D.C"
            }
        ]
    }
    
}

### Updating experiment record
POST http://localhost:3000/updateExperimentRecord HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "record": {
        "experimentRecord": {
            "record_id": 45,
            "LOT_NO": "66661",
            "project_title": "updated experiment name",
            "formulation_date": "2020-12-5",
            "preparation_date": "2020-12-5",
            "prepared_by": "Johnny Johnson",
            "quantity": "400",
            "notes": "Take 100g and Test stability in 54C for 2 weeks\nTake 100g and Test stability in 50C for 35 days\nProvide 100g to Sean/Cesar to conduct corrosion testing on Brass.",
            "preparation_reason": "To test improved F/T performance and reduce corrosion of the RTU formula while making it fall under our newly filed patents",
            "observations" : "",
            "total_percentage_w": "100.0",
            "total_AR": "355.6",
            "total_AD": "355.84",
            "date_created": "2020-12-5"
        }
    }   
}

### Updating Raw materials 
POST http://localhost:3000/updateRawMaterial HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "record": {
        "experimentRecord": {
            "record_id": 45
        },
        "RMList": [{
                "rm_id": 32,
                "raw_material_name": "chemical L63",
                "percentage_w": 11.11,
                "raw_material_lot": " ",
                "AR": 44.44,
                "AD": 44.48,
                "time_added": "2020-12-5",
                "notes": "this is an update"
            },
            {
                "rm_id": 33,
                "raw_material_name": "H2O2 50% EPA",
                "percentage_w": 21.11,
                "raw_material_lot": " ",
                "AR": 55.44,
                "AD": 44.48,
                "time_added": "2020-12-5",
                "notes": "this is another update"
            }
        ]
    }
}

### Updating experiment record
POST http://localhost:3000/updateHP HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "record": {
        "experimentRecord": {
            "record_id": 45
        },
        "HPList": [{
                "hp_id": 12,
                "experiment_name": "Trial 1",
                "N": 0.1000,
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "~ 0.8%",
                "date": "2020-12-5",
                "initials": "D.C"
            },
            {
                "hp_id": 13,
                "experiment_name": "Trial 2",
                "N": "",
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "new range",
                "date": "2020-12-5",
                "initials": ""
            },
            {
                "hp_id": 14,
                "experiment_name": "Average (Updated)",
                "N": "",
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "",
                "date": null,
                "initials": "D.C"
            }
        ],
        "HPStabilityList": [{
                "hp_id": 15,
                "experiment_name": "Trial 1",
                "N": 0.1000,
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "~ 0.75%",
                "date": "2020-12-5",
                "initials": "J.K"
            },
            {
                "hp_id": 16,
                "experiment_name": "Trial 2",
                "N": "",
                "M": "",
                "vol_change": "",
                "H2O2": 0.1000,
                "PH": 0.870,
                "accepted_range": "",
                "date": "2020-12-5",
                "initials": "D.C"
            }
        ]
    }
    
}

### Delete an experiment record
GET http://localhost:3000/deleteRecord?id=44 HTTP/1.1

### Delete a raw material record
POST http://localhost:3000/deleteRawMaterial HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "id": 32
}

### Delete an HP record
POST http://localhost:3000/deleteHP HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
    "id": 30
}